//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ihff_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestellingen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bestellingen()
        {
            this.BesteldeItems = new HashSet<BesteldeItems>();
        }
    
        public int Bestelling_ID { get; set; }
        public Nullable<int> Klant_ID { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<double> Prijs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BesteldeItems> BesteldeItems { get; set; }
        public virtual Klanten Klanten { get; set; }
        public virtual Klanten Klanten1 { get; set; }
        public virtual Klanten Klanten2 { get; set; }
        public virtual Klanten Klanten3 { get; set; }
    }
}
