//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ihff_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BesteldeItems
    {
        public int Bestelling_ID { get; set; }
        public int Product { get; set; }
        public Nullable<int> Aantal { get; set; }
        public Nullable<double> Prijs { get; set; }
    
        public virtual Bestellingen Bestellingen { get; set; }
        public virtual Producten Producten { get; set; }
    }
}
