//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ihff_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cultuur
    {
        public int Event_ID { get; set; }
        public string Naam { get; set; }
        public Nullable<int> Locatie { get; set; }
    
        public virtual Locaty Locaty { get; set; }
    }
}
