//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ihff_project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iHFF1617S_B3E : DbContext
    {
        public iHFF1617S_B3E()
            : base("name=iHFF1617S_B3E")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BesteldeItems> BesteldeItems { get; set; }
        public virtual DbSet<Bestellingen> Bestellingen { get; set; }
        public virtual DbSet<Cultuur> Cultuur { get; set; }
        public virtual DbSet<Films> Films { get; set; }
        public virtual DbSet<Klanten> Klanten { get; set; }
        public virtual DbSet<Locaties> Locaties { get; set; }
        public virtual DbSet<Medewerker> Medewerker { get; set; }
        public virtual DbSet<Producten> Producten { get; set; }
        public virtual DbSet<Restaurants> Restaurants { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Voorstellingen> Voorstellingen { get; set; }
    }
}
