//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ihff_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurants
    {
        public int Restaurant_ID { get; set; }
        public string Soort_Keuken { get; set; }
        public string Beschrijving_NL { get; set; }
        public string Beschrijving_EN { get; set; }
        public Nullable<System.TimeSpan> Openingstijd { get; set; }
        public Nullable<System.TimeSpan> Slutingstijd { get; set; }
        public string Emailadres { get; set; }
    
        public virtual Producten Producten { get; set; }
    }
}
