//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ihff_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voorstellingen
    {
        public int Product_ID { get; set; }
        public Nullable<int> Film_ID { get; set; }
        public Nullable<int> Dag { get; set; }
        public Nullable<System.TimeSpan> Start_Tijd { get; set; }
        public Nullable<System.TimeSpan> Eind_Tijd { get; set; }
        public Nullable<int> Plaatsen_Over { get; set; }
        public string Zaal { get; set; }
    
        public virtual Films Films { get; set; }
        public virtual Producten Producten { get; set; }
    }
}
